### ISSUE TITLE
Usage with sql.js

### ISSUE THREAD

**Issue by oskarer** [nolanlawson/node-websql#14]
I have a case where I need to run specific SQLite syntax not available in WebSQL, as well as run it inside a browser. Was thinking if it's possible to run node-websql with [sql.js](https://github.com/kripken/sql.js) out of the box, instead of using the node-dependent sqlite3 module.

Imagined this would work by just replacing sqlite3 with sql.js.. tried it out but didn't seem to work. No errors thrown and no luck in debugging either; 0cd0b89c997519cacf5e31041514d6fb6b2a1d1c.

Any ideas on what could be wrong here? Guessing this could be a neat feature to include in main repo as well if it works good. Thanks.

**Comment by nolanlawson** [comment]
`node-websql` as written is pretty heavily reliant on the API exposed by the `node-sqlite3` module ([details here](https://github.com/mapbox/node-sqlite3)).

Luckily there is a [custom API](https://github.com/nolanlawson/node-websql#custom-sqlite3-bindings) that can be used to delegate to your SQLite implementation of choice, which is undoubtedly what you would need to do in order to hook `node-websql` to `sql.js`. Hope that helps!

**Comment by nolanlawson** [comment]
Closing because I think this is out of scope; the custom API should be able to handle this.
