### ISSUE TITLE
Consider better-sqlite3 as an alternative to node-sqlite3

### ISSUE THREAD

**Issue by motin** [nolanlawson/node-websql#28]
They claim to be faster and better in all ways - https://www.npmjs.com/package/better-sqlite3 - are they a viable alternative to existing node-sqlite3?

**Comment by brettz9** [comment]
Their claim of the synchronous API being faster than the asynchronous one is particularly interesting to me given our need for the synchronous API with IndexedDBShim (to ensure proper timing)...

**Comment by nolanlawson** [comment]
Since it's possible to implement [custom bindings](https://github.com/nolanlawson/node-websql#custom-sqlite3-bindings), and since I have no plans to optimize the core of this library at the moment, I'm going to consider this an exercise for the reader. :) You can simply implement it on top of better-sqlite-3 if you'd like! Closing this issue for now, thanks for opening!
