### ISSUE TITLE
Feature request flash polyfill

### ISSUE THREAD

**Issue by EloB** [nolanlawson/node-websql#9]
I read the README and saw that you didn't want to make this a full polyfill but it would be awesome. I'm not 100% sure about this but I think flash has sqlite built-in. It would be awesome if we could implement an flash adapter. I don't think should be a major task todo...

**Comment by EloB** [comment]
I can team up with you and try to solve this :)

**Comment by nolanlawson** [comment]
There was briefly an effort to polyfill WebSQL over IndexedDB (see [WebSQLShim](https://github.com/agershun/WebSQLShim)), but it didn't get very far because you'd have to reimplement all of SQLite basically. As for Flash, I'm not super sure that that's the best horse to bet on at this point :wink:, but it could be a very interesting project!

If you want to get started with that, I would recommend looking at [the new custom API](https://github.com/nolanlawson/node-websql#custom-sqlite3-bindings). You can create a separate project that implements the abstract SQLite layer over Flash's SQLite and then it should work pretty easily. You can check out my [SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) which actually does this.

Closing this issue since I think it's more appropriate for a separate project, but I encourage you to give it a go!
